### ISSUE TITLE
"Dark Juno" theme option unavailable under Fedora 17/Gnome3

### ISSUE THREAD

**Issue by ntpeters** [rogerdudler/eclipse-ui-themes#7]
After extracting this into eclipse's dropins folder, Eclipse displays it under "Installed Software"; however, it is not listed in the themes dropdown menu under General > Appearance.

I'm on Fedora 17 x64, with Gnome 3.

**Comment by JTarasovic** [comment]
I am having the same problem. Here's the error from the workspace log:

`!ENTRY org.eclipse.osgi 4 0 2013-02-23 15:05:26.124`
`!MESSAGE Unexpected exception occurred loading manifest for bundle at the location: reference:file:dropins/plugins/com.github.eclipsecolortheme.themes_1.0.0.201207121019.jar.`
`!STACK 0`
`org.osgi.framework.BundleException: Error converting plugin at D:\Eclipse\dropins\plugins\com.github.eclipsecolortheme.themes_1.0.0.201207121019.jar.`
`at org.eclipse.core.runtime.internal.adaptor.EclipseStorageHook.generateManifest(EclipseStorageHook.java:451)`
`at org.eclipse.core.runtime.internal.adaptor.EclipseStorageHook.getGeneratedManifest0(EclipseStorageHook.java:414)`
`at org.eclipse.core.runtime.internal.adaptor.EclipseStorageHook.getGeneratedManifest(EclipseStorageHook.java:397)`
`at org.eclipse.core.runtime.internal.adaptor.EclipseStorageHook.createCachedManifest(EclipseStorageHook.java:392)`
`at org.eclipse.core.runtime.internal.adaptor.CachedManifest.getManifest(CachedManifest.java:42)`
`at org.eclipse.core.runtime.internal.adaptor.CachedManifest.get(CachedManifest.java:142)`
`at org.eclipse.core.runtime.internal.adaptor.CachedManifest.get(CachedManifest.java:1)`
`at org.eclipse.osgi.framework.internal.core.ManifestLocalization.lookupResourceBundle(ManifestLocalization.java:104)`
`at org.eclipse.osgi.framework.internal.core.ManifestLocalization.getResourceBundle(ManifestLocalization.java:91)`
`at org.eclipse.osgi.framework.internal.core.ManifestLocalization.getHeaders(ManifestLocalization.java:52)`
`at org.eclipse.osgi.framework.internal.core.AbstractBundle.getHeaders(AbstractBundle.java:965)`
`at org.eclipse.osgi.framework.internal.core.AbstractBundle.getHeaders(AbstractBundle.java:912)`
`at org.eclipse.osgi.framework.internal.core.AbstractBundle.uninstallWorkerPrivileged(AbstractBundle.java:837)`
`at org.eclipse.osgi.framework.internal.core.AbstractBundle$4.run(AbstractBundle.java:786)`
`at java.security.AccessController.doPrivileged(Native Method)`
`at org.eclipse.osgi.framework.internal.core.AbstractBundle.uninstallWorker(AbstractBundle.java:810)`
`at org.eclipse.osgi.framework.internal.core.AbstractBundle.uninstall(AbstractBundle.java:784)`
`at org.eclipse.equinox.internal.simpleconfigurator.ConfigApplier.uninstallBundles(ConfigApplier.java:375)`
`at org.eclipse.equinox.internal.simpleconfigurator.ConfigApplier.install(ConfigApplier.java:90)`
`at org.eclipse.equinox.internal.simpleconfigurator.SimpleConfiguratorImpl.applyConfiguration(SimpleConfiguratorImpl.java:129)`
`at org.eclipse.equinox.internal.simpleconfigurator.SimpleConfiguratorImpl.applyConfiguration(SimpleConfiguratorImpl.java:143)`
`at org.eclipse.equinox.internal.simpleconfigurator.Activator.start(Activator.java:48)`
`at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextImpl.java:711)`
`at java.security.AccessController.doPrivileged(Native Method)`
`at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:702)`
`at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:683)`
`at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:381)`
`at org.eclipse.osgi.framework.internal.core.AbstractBundle.resume(AbstractBundle.java:390)`
`at org.eclipse.osgi.framework.internal.core.Framework.resumeBundle(Framework.java:1176)`
`at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:559)`
`at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:544)`
`at org.eclipse.osgi.framework.internal.core.StartLevelManager.incFWSL(StartLevelManager.java:457)`
`at org.eclipse.osgi.framework.internal.core.StartLevelManager.doSetStartLevel(StartLevelManager.java:243)`
`at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:438)`
`at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:1)`
`at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)`
`at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)`
`Caused by: org.eclipse.osgi.service.pluginconversion.PluginConversionException: Error parsing plugin manifest. Missing attribute "id" in element "plugin".`
`at org.eclipse.core.runtime.internal.adaptor.PluginConverterImpl.fillPluginInfo(PluginConverterImpl.java:127)`
`at org.eclipse.core.runtime.internal.adaptor.PluginConverterImpl.convertManifest(PluginConverterImpl.java:714)`
`at org.eclipse.core.runtime.internal.adaptor.EclipseStorageHook.generateManifest(EclipseStorageHook.java:448)`
`... 36 more`
